-- V002: Seed company_info from company_info.csv
-- ATS and ATS link derived from which career page URL is present

INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('Adidas', '', '', '', '');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('Adobe', '', '', 'workday', 'https://adobe.wd5.myworkdayjobs.com/external_experienced');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('Agoda', '', '', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/Agoda/jobs');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('Air France KLM digital', '', '', '', '');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('Airbnb', '', '', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/Airbnb/jobs');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('Airbus', '', '', 'workday', 'https://ag.wd3.myworkdayjobs.com/Airbus');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('Amadeus', '', '', 'workday', 'https://amadeus.wd502.myworkdayjobs.com/jobs');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('Amazon', '', '', '', '');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('AMD', '', '', '', '');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('American Airlines tech', '', '', 'workday', 'https://aaregional.wd503.myworkdayjobs.com/Search');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('Amex', '', '', 'workday', 'https://travelhrportal.wd1.myworkdayjobs.com/Jobs');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('Apple', '', '', '', '');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('Atlassian', '', '', '', '');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('Bank of America', '', '', 'workday', 'https://ghr.wd1.myworkdayjobs.com/lateral-ba_continuum');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('Barclays', '', '', 'workday', 'https://barclays.wd3.myworkdayjobs.com/External_Career_Site_Barclays');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('BharatPe', '', '', '', '');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('Bloomberg', '', '', 'workday', 'https://bloomberg.wd1.myworkdayjobs.com/Bloombergindustrygroup_External_Career_Site');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('Blue Yonder', '', '', 'workday', 'https://jda.wd5.myworkdayjobs.com/JDA_Careers/3/refreshFacet/318c8bb6f553100021d223d9780d30be');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('BlueDart', '', '', '', '');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('BMW', '', '', '', '');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('BNP Paribas', '', '', '', '');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('Boeing', '', '', 'workday', 'https://boeing.wd1.myworkdayjobs.com/EXTERNAL_CAREERS');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('Booking Holdings', '', '', 'workday', 'https://priceline.wd1.myworkdayjobs.com/BookingHoldings');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('BP', '', '', 'workday', 'https://bpinternational.wd3.myworkdayjobs.com/bpCareers/login');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('BYD', '', '', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/BYD/jobs');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('Caterpillar', '', '', 'workday', 'https://cat.wd5.myworkdayjobs.com/CaterpillarCareers/login');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('Citi', '', '', 'workday', 'https://citi.wd5.myworkdayjobs.com/2/1/refreshFacet/318c8bb6f553100021d223d9780d30be');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('Cloudflare', '', '', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/Cloudflare/jobs');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('Confluent', '', '', '', '');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('Costco', '', '', '', '');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('CRED', '', '', 'workday', 'https://broadridge.wd5.myworkdayjobs.com/Careers');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('Databricks', '', '', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/Databricks/jobs');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('Delta', '', '', '', '');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('Deutsche Bank', '', '', 'workday', 'https://db.wd3.myworkdayjobs.com/DBWebsite');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('DHL', '', '', '', '');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('Docker', '', '', '', '');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('DoorDash', '', '', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/DoorDashIndia/jobs/');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('Emirates', '', '', '', '');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('Etihad', '', '', '', '');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('Expedia', '', '', 'workday', 'https://expedia.wd108.myworkdayjobs.com/en-US/search/job/India---Bangalore/Contract-Recruiter_R-100354');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('ExxonMobil', '', '', '', '');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('Fidelity', '', '', 'workday', 'https://fil.wd3.myworkdayjobs.com/001');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('Flipkart', '', '', '', '');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('Ford', '', '', '', '');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('General Motors', '', '', 'workday', 'https://fordfoundation.wd1.myworkdayjobs.com/FordFoundationCareerPage');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('Goldman Sachs', '', '', '', '');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('Google', '', '', '', '');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('HashiCorp', '', '', '', '');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('Hitachi', '', '', 'workday', 'https://hitachi.wd1.myworkdayjobs.com/hitachi');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('Home Depot', '', '', 'workday', 'https://homedepot.wd5.myworkdayjobs.com/CareerDepot/login');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('Honda', '', '', '', '');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('Honeywell', '', '', '', '');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('Hyundai', '', '', '', '');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('IKEA', '', '', '', '');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('Intuit', '', '', '', '');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('John Deere', '', '', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/deeretechstack/jobs/');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('JP Morgan', '', '', '', '');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('Kia', '', '', '', '');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('LG', '', '', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/lgelectronics/jobs/');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('Linekdin', '', '', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/LinkedIn/jobs');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('Lowe''s', '', '', 'workday', 'https://lowes.wd5.myworkdayjobs.com/LWS_External_CS/login');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('LSEG', '', '', 'workday', 'https://lseg.wd3.myworkdayjobs.com/Careers');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('Lufthansa Systems', '', '', '', '');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('Lyft', '', '', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/Lyft/jobs');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('Maersk', '', '', 'workday', 'https://maersk.wd3.myworkdayjobs.com/Maersk_Careers');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('Mastercard', '', '', 'workday', 'https://mastercard.wd1.myworkdayjobs.com/CorporateCareers');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('Mercedes', '', '', '', '');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('Meta', '', '', '', '');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('Microsoft', '', '', '', '');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('MongoDB', '', '', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/MongoDB/jobs');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('Morgan Stanley', '', '', 'workday', 'https://ms.wd5.myworkdayjobs.com/External/job/Bengaluru-India/Software-Engineer---AI--Data---Agentic-Systems---Director--Software-Engineering------------------------------------------------------------------------------------------------------------------------------------------------_PT-JR031694-1');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('Nasdaq', '', '', 'workday', 'https://nasdaq.wd1.myworkdayjobs.com/Global_External_Site');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('Netflix', '', '', 'workday', 'https://netflix.wd1.myworkdayjobs.com/Netflix');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('Nike', '', '', 'workday', 'https://nike.wd1.myworkdayjobs.com/nke/');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('Nvidia', '', '', 'workday', 'https://nvidia.wd5.myworkdayjobs.com/NVIDIAExternalCareerSite');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('Oracle', '', '', '', '');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('PayPal', '', '', 'workday', 'https://paypal.wd1.myworkdayjobs.com/jobs');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('PepsiCo', '', '', '', '');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('Philips', '', '', 'workday', 'https://philips.wd3.myworkdayjobs.com/en-US/jobs-and-careers');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('Priceline', '', '', 'workday', 'https://priceline.wd1.myworkdayjobs.com/Priceline');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('Qatar Airways', '', '', '', '');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('Qualcomm', '', '', '', '');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('Rakuten', '', '', 'workday', 'https://rakuten.wd1.myworkdayjobs.com/RakutenInc');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('Red Hat', '', '', 'workday', 'https://redhat.wd5.myworkdayjobs.com/Jobs');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('Rippling', '', '', '', '');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('Rivian', '', '', '', '');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('S&P Global', '', '', 'workday', 'https://spgi.wd5.myworkdayjobs.com/SPGI_Careers');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('Sabre', '', '', 'workday', 'https://sabre.wd1.myworkdayjobs.com/SabreJobs');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('Salesforce', '', '', 'workday', 'https://salesforce.wd12.myworkdayjobs.com/External_Career_Site');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('Samsung', '', '', 'workday', 'https://sec.wd3.myworkdayjobs.com/Samsung_Careers');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('SAP Labs', '', '', '', '');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('Schneider Electric', '', '', '', '');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('ServiceNow', '', '', '', '');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('Shell', '', '', 'workday', 'https://shell.wd3.myworkdayjobs.com/ShellCareers');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('Siemens', '', '', 'workday', 'https://onehealthineers.wd3.myworkdayjobs.com/SHSJB');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('Singapore Airlines', '', '', '', '');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('Société Générale', '', '', '', '');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('Sony', '', '', 'workday', 'https://sonyglobal.wd1.myworkdayjobs.com/SonyGlobalCareers');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('Splunk', '', '', '', '');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('Stripe', '', '', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/Stripe/jobs');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('Target', '', '', 'workday', 'https://target.wd5.myworkdayjobs.com/targetcareers');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('Tesla', '', '', '', '');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('Texas Instruments', '', '', '', '');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('Toshiba', '', '', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/toshibaglobalcommercesolutions/jobs/');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('Toyota', '', '', 'workday', 'https://toyota.wd503.myworkdayjobs.com/TMNA');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('Trivago', '', '', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/Trivago/jobs');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('Uber', '', '', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/uberfreight/jobs/');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('UBS', '', '', '', '');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('United Airlines tech', '', '', '', '');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('Visa', '', '', '', '');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('VMware', '', '', 'workday', 'https://broadcom.wd1.myworkdayjobs.com/External_Career');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('Volkswagen', '', '', '', '');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('Walmart', '', '', '', '');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('Wells Fargo', '', '', 'workday', 'https://wf.wd1.myworkdayjobs.com/WellsFargoJobs');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('Western Digital', '', '', '', '');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('Zoho', '', '', '', '');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('BlackRock', '', '', 'workday', 'https://blackrock.wd1.myworkdayjobs.com/BlackRock_Professional/2/refreshFacet/318c8bb6f553100021d223d9780d30be');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('Fourkites', '', '', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/Fourkites/jobs');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('Puma', '', '', 'workday', 'https://trafigura.wd3.myworkdayjobs.com/Puma_Energy_Careers');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('Cleartrip', '', '', '', '');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('Myntra', '', '', '', '');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('Media dot net', '', '', '', '');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('TSMC', '', '', '', '');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('Rubrik', '', '', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/Rubrik/jobs');
INSERT IGNORE INTO company_info (company_name, base_country, target_location, ats, ats_link) VALUES ('Jetbrains', '', '', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/jetbrains/jobs/');
